"use strict";
exports.__esModule = true;
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var ensureOwner_middleware_1 = require("../middlewares/ensureOwner.middleware");
var user_validator_1 = require("../validators/user.validator");
var validateRequest_middleware_1 = require("../middlewares/validateRequest.middleware");
var router = (0, express_1.Router)();
router.get("/:username", user_controller_1.getUserProfile);
router.patch("/:id", auth_middleware_1.requireAuth, user_validator_1.updateUserValidator, validateRequest_middleware_1.validateRequest, (0, ensureOwner_middleware_1.ensureOwner)("id"), user_controller_1.updateUserProfile);
exports["default"] = router;
